[build]
builder = "DOCKERFILE"
dockerfilePath = "pt_booking_shadow/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
