[build]
builder = "DOCKERFILE"
dockerfilePath = "cancellation_finalizer/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

